/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'

const AddingStationsLazyRouteImport = createFileRoute('/adding-stations')()
const LegalChangelogLazyRouteImport = createFileRoute('/legal/changelog')()
const LegalCookiesLazyRouteImport = createFileRoute('/legal/cookies')()
const LegalPrivacyLazyRouteImport = createFileRoute('/legal/privacy')()
const LegalSecurityLazyRouteImport = createFileRoute('/legal/security')()
const LegalTermsLazyRouteImport = createFileRoute('/legal/terms')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AddingStationsLazyRoute = AddingStationsLazyRouteImport.update({
  id: '/adding-stations',
  path: '/adding-stations',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/adding-stations.lazy').then((d) => d.Route),
)
const LegalChangelogLazyRoute = LegalChangelogLazyRouteImport.update({
  id: '/legal/changelog',
  path: '/legal/changelog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/legal/changelog.lazy').then((d) => d.Route),
)
const LegalCookiesLazyRoute = LegalCookiesLazyRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/legal/cookies.lazy').then((d) => d.Route))
const LegalPrivacyLazyRoute = LegalPrivacyLazyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/legal/privacy.lazy').then((d) => d.Route))
const LegalSecurityLazyRoute = LegalSecurityLazyRouteImport.update({
  id: '/legal/security',
  path: '/legal/security',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/legal/security.lazy').then((d) => d.Route),
)
const LegalTermsLazyRoute = LegalTermsLazyRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/legal/terms.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/adding-stations': typeof AddingStationsLazyRoute
  '/legal/changelog': typeof LegalChangelogLazyRoute
  '/legal/cookies': typeof LegalCookiesLazyRoute
  '/legal/privacy': typeof LegalPrivacyLazyRoute
  '/legal/security': typeof LegalSecurityLazyRoute
  '/legal/terms': typeof LegalTermsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/adding-stations': typeof AddingStationsLazyRoute
  '/legal/changelog': typeof LegalChangelogLazyRoute
  '/legal/cookies': typeof LegalCookiesLazyRoute
  '/legal/privacy': typeof LegalPrivacyLazyRoute
  '/legal/security': typeof LegalSecurityLazyRoute
  '/legal/terms': typeof LegalTermsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/adding-stations': typeof AddingStationsLazyRoute
  '/legal/changelog': typeof LegalChangelogLazyRoute
  '/legal/cookies': typeof LegalCookiesLazyRoute
  '/legal/privacy': typeof LegalPrivacyLazyRoute
  '/legal/security': typeof LegalSecurityLazyRoute
  '/legal/terms': typeof LegalTermsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/adding-stations'
    | '/legal/changelog'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/adding-stations'
    | '/legal/changelog'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/adding-stations'
    | '/legal/changelog'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AddingStationsLazyRoute: typeof AddingStationsLazyRoute
  LegalChangelogLazyRoute: typeof LegalChangelogLazyRoute
  LegalCookiesLazyRoute: typeof LegalCookiesLazyRoute
  LegalPrivacyLazyRoute: typeof LegalPrivacyLazyRoute
  LegalSecurityLazyRoute: typeof LegalSecurityLazyRoute
  LegalTermsLazyRoute: typeof LegalTermsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adding-stations': {
      id: '/adding-stations'
      path: '/adding-stations'
      fullPath: '/adding-stations'
      preLoaderRoute: typeof AddingStationsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/changelog': {
      id: '/legal/changelog'
      path: '/legal/changelog'
      fullPath: '/legal/changelog'
      preLoaderRoute: typeof LegalChangelogLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/legal/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AddingStationsLazyRoute: AddingStationsLazyRoute,
  LegalChangelogLazyRoute: LegalChangelogLazyRoute,
  LegalCookiesLazyRoute: LegalCookiesLazyRoute,
  LegalPrivacyLazyRoute: LegalPrivacyLazyRoute,
  LegalSecurityLazyRoute: LegalSecurityLazyRoute,
  LegalTermsLazyRoute: LegalTermsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
