/** Full station-country directory (exact directory name + ISO 3166-1 code,
 * most stations first). Generated 2026-09-23 from /json/countries ordered by
 * stationcount (247 rows; empty-name and duplicate rows dropped) — regen to
 * refresh. Lazy-loaded by the picker only; the popular shortlist lives in
 * `country-popular.ts` and stays in the initial bundle. */
export interface DirectoryCountry {
  name: string;
  iso: string;
}

export const DIRECTORY_COUNTRIES: DirectoryCountry[] = [
  { name: "The United States Of America", iso: "US" },
  { name: "Germany", iso: "DE" },
  { name: "France", iso: "FR" },
  { name: "The Russian Federation", iso: "RU" },
  { name: "Mexico", iso: "MX" },
  { name: "The United Kingdom Of Great Britain And Northern Ireland", iso: "GB" },
  { name: "Greece", iso: "GR" },
  { name: "China", iso: "CN" },
  { name: "Australia", iso: "AU" },
  { name: "Italy", iso: "IT" },
  { name: "Brazil", iso: "BR" },
  { name: "Canada", iso: "CA" },
  { name: "The Netherlands", iso: "NL" },
  { name: "Spain", iso: "ES" },
  { name: "Argentina", iso: "AR" },
  { name: "Poland", iso: "PL" },
  { name: "India", iso: "IN" },
  { name: "Romania", iso: "RO" },
  { name: "The Philippines", iso: "PH" },
  { name: "The United Arab Emirates", iso: "AE" },
  { name: "Türkiye", iso: "TR" },
  { name: "Colombia", iso: "CO" },
  { name: "Switzerland", iso: "CH" },
  { name: "Indonesia", iso: "ID" },
  { name: "Chile", iso: "CL" },
  { name: "Belgium", iso: "BE" },
  { name: "Serbia", iso: "RS" },
  { name: "Hungary", iso: "HU" },
  { name: "Ukraine", iso: "UA" },
  { name: "Austria", iso: "AT" },
  { name: "Portugal", iso: "PT" },
  { name: "Uganda", iso: "UG" },
  { name: "Bulgaria", iso: "BG" },
  { name: "Czechia", iso: "CZ" },
  { name: "Croatia", iso: "HR" },
  { name: "Peru", iso: "PE" },
  { name: "Sweden", iso: "SE" },
  { name: "Denmark", iso: "DK" },
  { name: "South Africa", iso: "ZA" },
  { name: "Ireland", iso: "IE" },
  { name: "New Zealand", iso: "NZ" },
  { name: "Taiwan, Republic Of China", iso: "TW" },
  { name: "Slovakia", iso: "SK" },
  { name: "Bolivarian Republic Of Venezuela", iso: "VE" },
  { name: "Bosnia And Herzegovina", iso: "BA" },
  { name: "Ecuador", iso: "EC" },
  { name: "Uruguay", iso: "UY" },
  { name: "Nepal", iso: "NP" },
  { name: "Israel", iso: "IL" },
  { name: "Finland", iso: "FI" },
  { name: "Slovenia", iso: "SI" },
  { name: "Japan", iso: "JP" },
  { name: "Norway", iso: "NO" },
  { name: "Latvia", iso: "LV" },
  { name: "The Dominican Republic", iso: "DO" },
  { name: "Estonia", iso: "EE" },
  { name: "The Republic Of Korea", iso: "KR" },
  { name: "Saudi Arabia", iso: "SA" },
  { name: "Thailand", iso: "TH" },
  { name: "Afghanistan", iso: "AF" },
  { name: "Ghana", iso: "GH" },
  { name: "Lithuania", iso: "LT" },
  { name: "Hong Kong", iso: "HK" },
  { name: "Malaysia", iso: "MY" },
  { name: "The Republic Of Moldova", iso: "MD" },
  { name: "Sri Lanka", iso: "LK" },
  { name: "Egypt", iso: "EG" },
  { name: "Belarus", iso: "BY" },
  { name: "Kenya", iso: "KE" },
  { name: "Guatemala", iso: "GT" },
  { name: "Nigeria", iso: "NG" },
  { name: "Algeria", iso: "DZ" },
  { name: "Morocco", iso: "MA" },
  { name: "Lebanon", iso: "LB" },
  { name: "Tunisia", iso: "TN" },
  { name: "Pakistan", iso: "PK" },
  { name: "Bolivia", iso: "BO" },
  { name: "Paraguay", iso: "PY" },
  { name: "Singapore", iso: "SG" },
  { name: "El Salvador", iso: "SV" },
  { name: "Costa Rica", iso: "CR" },
  { name: "Puerto Rico", iso: "PR" },
  { name: "Albania", iso: "AL" },
  { name: "Cyprus", iso: "CY" },
  { name: "Jamaica", iso: "JM" },
  { name: "Montenegro", iso: "ME" },
  { name: "Republic Of North Macedonia", iso: "MK" },
  { name: "Honduras", iso: "HN" },
  { name: "Kazakhstan", iso: "KZ" },
  { name: "Reunion", iso: "RE" },
  { name: "Azerbaijan", iso: "AZ" },
  { name: "Haiti", iso: "HT" },
  { name: "Luxembourg", iso: "LU" },
  { name: "Senegal", iso: "SN" },
  { name: "Syrian Arab Republic", iso: "SY" },
  { name: "Vietnam", iso: "VN" },
  { name: "The United States Minor Outlying Islands", iso: "UM" },
  { name: "Georgia", iso: "GE" },
  { name: "Panama", iso: "PA" },
  { name: "Islamic Republic Of Iran", iso: "IR" },
  { name: "Trinidad And Tobago", iso: "TT" },
  { name: "Iceland", iso: "IS" },
  { name: "Jordan", iso: "JO" },
  { name: "Iraq", iso: "IQ" },
  { name: "Nicaragua", iso: "NI" },
  { name: "Ethiopia", iso: "ET" },
  { name: "Macao", iso: "MO" },
  { name: "Bangladesh", iso: "BD" },
  { name: "Cuba", iso: "CU" },
  { name: "Qatar", iso: "QA" },
  { name: "Curacao", iso: "CW" },
  { name: "Barbados", iso: "BB" },
  { name: "United Republic Of Tanzania", iso: "TZ" },
  { name: "Bahrain", iso: "BH" },
  { name: "Cabo Verde", iso: "CV" },
  { name: "Saint Lucia", iso: "LC" },
  { name: "The Democratic Republic Of The Congo", iso: "CD" },
  { name: "Namibia", iso: "NA" },
  { name: "Kosovo", iso: "XK" },
  { name: "Guadeloupe", iso: "GP" },
  { name: "American Samoa", iso: "AS" },
  { name: "Kuwait", iso: "KW" },
  { name: "Mauritius", iso: "MU" },
  { name: "The Holy See", iso: "VA" },
  { name: "Armenia", iso: "AM" },
  { name: "The Faroe Islands", iso: "FO" },
  { name: "Yemen", iso: "YE" },
  { name: "Madagascar", iso: "MG" },
  { name: "Uzbekistan", iso: "UZ" },
  { name: "Malta", iso: "MT" },
  { name: "Angola", iso: "AO" },
  { name: "Mali", iso: "ML" },
  { name: "French Polynesia", iso: "PF" },
  { name: "The Democratic Peoples Republic Of Korea", iso: "KP" },
  { name: "State Of Palestine", iso: "PS" },
  { name: "Suriname", iso: "SR" },
  { name: "Guyana", iso: "GY" },
  { name: "Andorra", iso: "AD" },
  { name: "Bonaire", iso: "BQ" },
  { name: "Coted Ivoire", iso: "CI" },
  { name: "Saint Vincent And The Grenadines", iso: "VC" },
  { name: "Libya", iso: "LY" },
  { name: "Martinique", iso: "MQ" },
  { name: "The Cayman Islands", iso: "KY" },
  { name: "Rwanda", iso: "RW" },
  { name: "Oman", iso: "OM" },
  { name: "Antarctica", iso: "AQ" },
  { name: "Aruba", iso: "AW" },
  { name: "The Bahamas", iso: "BS" },
  { name: "Malawi", iso: "MW" },
  { name: "Monaco", iso: "MC" },
  { name: "US Virgin Islands", iso: "VI" },
  { name: "Mongolia", iso: "MN" },
  { name: "Cambodia", iso: "KH" },
  { name: "New Caledonia", iso: "NC" },
  { name: "Isle Of Man", iso: "IM" },
  { name: "Burkina Faso", iso: "BF" },
  { name: "Maldives", iso: "MV" },
  { name: "Kyrgyzstan", iso: "KG" },
  { name: "Mozambique", iso: "MZ" },
  { name: "Togo", iso: "TG" },
  { name: "British Indian Ocean Territory", iso: "IO" },
  { name: "San Marino", iso: "SM" },
  { name: "Dominica", iso: "DM" },
  { name: "Gibraltar", iso: "GI" },
  { name: "Bermuda", iso: "BM" },
  { name: "The Comoros", iso: "KM" },
  { name: "The Sudan", iso: "SD" },
  { name: "Antigua And Barbuda", iso: "AG" },
  { name: "Zambia", iso: "ZM" },
  { name: "Myanmar", iso: "MM" },
  { name: "Anguilla", iso: "AI" },
  { name: "Greenland", iso: "GL" },
  { name: "Botswana", iso: "BW" },
  { name: "Turkmenistan", iso: "TM" },
  { name: "Grenada", iso: "GD" },
  { name: "Vanuatu", iso: "VU" },
  { name: "Eritrea", iso: "ER" },
  { name: "Brunei Darussalam", iso: "BN" },
  { name: "The Falkland Islands Malvinas", iso: "FK" },
  { name: "Guam", iso: "GU" },
  { name: "Benin", iso: "BJ" },
  { name: "Seychelles", iso: "SC" },
  { name: "Guinea", iso: "GN" },
  { name: "Christmas Island", iso: "CX" },
  { name: "Saint Kitts And Nevis", iso: "KN" },
  { name: "French Guiana", iso: "GF" },
  { name: "The Central African Republic", iso: "CF" },
  { name: "Zimbabwe", iso: "ZW" },
  { name: "Palau", iso: "PW" },
  { name: "Sierra Leone", iso: "SL" },
  { name: "Cameroon", iso: "CM" },
  { name: "Somalia", iso: "SO" },
  { name: "Tonga", iso: "TO" },
  { name: "Burundi", iso: "BI" },
  { name: "Mayotte", iso: "YT" },
  { name: "Belize", iso: "BZ" },
  { name: "The Lao Peoples Democratic Republic", iso: "LA" },
  { name: "Montserrat", iso: "MS" },
  { name: "British Virgin Islands", iso: "VG" },
  { name: "South Sudan", iso: "SS" },
  { name: "The French Southern Territories", iso: "TF" },
  { name: "The Niger", iso: "NE" },
  { name: "Sao Tome And Principe", iso: "ST" },
  { name: "Ascension And Tristan Da Cunha Saint Helena", iso: "SH" },
  { name: "Saint Pierre And Miquelon", iso: "PM" },
  { name: "The Marshall Islands", iso: "MH" },
  { name: "The Congo", iso: "CG" },
  { name: "Jersey", iso: "JE" },
  { name: "Wallis And Futuna", iso: "WF" },
  { name: "Guinea Bissau", iso: "GW" },
  { name: "Tajikistan", iso: "TJ" },
  { name: "Equatorial Guinea", iso: "GQ" },
  { name: "Guernsey", iso: "GG" },
  { name: "Gabon", iso: "GA" },
  { name: "Niue", iso: "NU" },
  { name: "Chad", iso: "TD" },
  { name: "Liechtenstein", iso: "LI" },
  { name: "Aland Islands", iso: "AX" },
  { name: "Tuvalu", iso: "TV" },
  { name: "Eswatini", iso: "SZ" },
  { name: "Timor Leste", iso: "TL" },
  { name: "Kiribati", iso: "KI" },
  { name: "Djibouti", iso: "DJ" },
  { name: "Bhutan", iso: "BT" },
  { name: "Lesotho", iso: "LS" },
  { name: "Dutch Part Sint Maarten", iso: "SX" },
  { name: "Svalbard And Jan Mayen", iso: "SJ" },
  { name: "French Part Saint Martin", iso: "MF" },
  { name: "Solomon Islands", iso: "SB" },
  { name: "The Cocos Keeling Islands", iso: "CC" },
  { name: "Nauru", iso: "NR" },
  { name: "The Turks And Caicos Islands", iso: "TC" },
  { name: "Liberia", iso: "LR" },
  { name: "Mauritania", iso: "MR" },
  { name: "Papua New Guinea", iso: "PG" },
  { name: "The Gambia", iso: "GM" },
  { name: "The Cook Islands", iso: "CK" },
  { name: "Federated States Of Micronesia", iso: "FM" },
  { name: "Fiji", iso: "FJ" },
];
