/** Full station-language directory (name + ISO 639 code, most stations first).
 * Generated 2026-09-21 from /json/languages (624 rows) — regen to refresh.
 * Lazy-loaded by the picker only; the popular shortlist lives in
 * `language-popular.ts` and stays in the initial bundle. */
export interface DirectoryLanguage {
  name: string;
  code: string;
}

export const DIRECTORY_LANGUAGES: DirectoryLanguage[] = [
  { name: "english", code: "en" },
  { name: "spanish", code: "es" },
  { name: "german", code: "de" },
  { name: "french", code: "fr" },
  { name: "chinese", code: "zh" },
  { name: "russian", code: "ru" },
  { name: "italian", code: "it" },
  { name: "greek", code: "el" },
  { name: "dutch", code: "nl" },
  { name: "polish", code: "pl" },
  { name: "portuguese", code: "pt" },
  { name: "arabic", code: "ar" },
  { name: "american english", code: "" },
  { name: "hindi", code: "hi" },
  { name: "brazilian portuguese", code: "" },
  { name: "romanian", code: "ro" },
  { name: "serbian", code: "sr" },
  { name: "turkish", code: "tr" },
  { name: "tamil", code: "ta" },
  { name: "hungarian", code: "hu" },
  { name: "español mexico", code: "" },
  { name: "ukrainian", code: "uk" },
  { name: "croatian", code: "hr" },
  { name: "indonesian", code: "id" },
  { name: "czech", code: "cs" },
  { name: "romania", code: "" },
  { name: "română", code: "" },
  { name: "castellano. español", code: "" },
  { name: "español argentina", code: "" },
  { name: "nepali", code: "ne" },
  { name: "english uk", code: "" },
  { name: "bulgarian", code: "bg" },
  { name: "filipino", code: "" },
  { name: "japanese", code: "ja" },
  { name: "engilsh", code: "" },
  { name: "slovak", code: "sk" },
  { name: "swedish", code: "sv" },
  { name: "cantonese", code: "yue" },
  { name: "язык: русский", code: "" },
  { name: "español internacional", code: "" },
  { name: "korean", code: "ko" },
  { name: "português  brasil", code: "" },
  { name: "danish", code: "da" },
  { name: "catalan", code: "ca" },
  { name: "bosnian", code: "bs" },
  { name: "português (brasil)", code: "" },
  { name: "español - latinoamerica", code: "" },
  { name: "deutsch fränkisch", code: "" },
  { name: "malayalam", code: "ml" },
  { name: "finnish", code: "fi" },
  { name: "british english", code: "" },
  { name: "slovenian", code: "sl" },
  { name: "thai", code: "th" },
  { name: "hebrew", code: "he" },
  { name: "francaise", code: "" },
  { name: "bahasa indonesia", code: "" },
  { name: "punjabi", code: "" },
  { name: "luganda", code: "" },
  { name: "portugues do brasil", code: "" },
  { name: "akan", code: "ak" },
  { name: "norwegian", code: "no" },
  { name: "espaňol", code: "" },
  { name: "espanish", code: "" },
  { name: "românä", code: "" },
  { name: "urdu", code: "ur" },
  { name: "swiss german", code: "gsw" },
  { name: "latvian", code: "lv" },
  { name: "pt-br", code: "" },
  { name: "ukranian", code: "" },
  { name: "estonian", code: "et" },
  { name: "español chile", code: "" },
  { name: "español colombia", code: "" },
  { name: "mandarin", code: "cmn" },
  { name: "hokkien", code: "" },
  { name: "swahili", code: "sw" },
  { name: "sinhala", code: "si" },
  { name: "belarusian", code: "be" },
  { name: "turkçe", code: "" },
  { name: "malay", code: "ms" },
  { name: "lithuanian", code: "lt" },
  { name: "telugu", code: "te" },
  { name: "persian", code: "fa" },
  { name: "macedonian", code: "mk" },
  { name: "kazakh", code: "kk" },
  { name: "kurdish", code: "ku" },
  { name: "português (br)", code: "" },
  { name: "tagalog", code: "tl" },
  { name: "basque", code: "eu" },
  { name: "kannada", code: "kn" },
  { name: "afrikaans", code: "af" },
  { name: "albanian", code: "sq" },
  { name: "zh", code: "" },
  { name: "azerbaijani", code: "az" },
  { name: "montenegro", code: "" },
  { name: "flemish", code: "" },
  { name: "low german", code: "nds" },
  { name: "español peruano", code: "" },
  { name: "mongolian", code: "mn" },
  { name: "georgian", code: "ka" },
  { name: "deutch", code: "" },
  { name: "rus", code: "" },
  { name: "bangla", code: "" },
  { name: "portugues do braasil", code: "" },
  { name: "creole", code: "" },
  { name: "galician", code: "gl" },
  { name: "türkisch", code: "" },
  { name: "bengali", code: "bn" },
  { name: "haitian creole", code: "" },
  { name: "icelandic", code: "is" },
  { name: "inglés/portugués/español", code: "" },
  { name: "armenian", code: "hy" },
  { name: "français - lëtzebuergesch", code: "" },
  { name: "gernan", code: "" },
  { name: "montenegrin", code: "" },
  { name: "asunción", code: "" },
  { name: "norsk", code: "" },
  { name: "العربية", code: "" },
  { name: "willemstad", code: "" },
  { name: "franch", code: "" },
  { name: "latin", code: "la" },
  { name: "engilsh uk", code: "" },
  { name: "norddeutsch", code: "" },
  { name: "amharic", code: "am" },
  { name: "español ecuador", code: "" },
  { name: "irish", code: "ga" },
  { name: "kurdi", code: "" },
  { name: "englsih", code: "" },
  { name: "moldovian", code: "" },
  { name: "spain", code: "" },
  { name: "tibetan", code: "bo" },
  { name: "vietnamese", code: "vi" },
  { name: "uyghur", code: "" },
  { name: "kapampangan", code: "" },
  { name: "english/ españa/ russian /francia /italia", code: "" },
  { name: "javanese", code: "jv" },
  { name: "moroccan arabic", code: "" },
  { name: "tatar", code: "tt" },
  { name: "#spanish", code: "" },
  { name: "faroese", code: "fo" },
  { name: "bambara", code: "bm" },
  { name: "ancient greek", code: "" },
  { name: "galego", code: "" },
  { name: "عربي", code: "" },
  { name: "luxembourgish", code: "lb" },
  { name: "româna", code: "" },
  { name: "yoruba", code: "yo" },
  { name: "lusoga", code: "" },
  { name: "breton", code: "br" },
  { name: "tunisian", code: "" },
  { name: "khmer", code: "km" },
  { name: "slovenski", code: "" },
  { name: "tr", code: "" },
  { name: "odia", code: "" },
  { name: "flammish", code: "" },
  { name: "bhojpuri", code: "" },
  { name: "quechua", code: "qu" },
  { name: "ilocano", code: "" },
  { name: "estonia", code: "" },
  { name: "sorbian", code: "" },
  { name: "croatia", code: "" },
  { name: "cebuano", code: "" },
  { name: "gaelic", code: "gd" },
  { name: "английский", code: "" },
  { name: "brasil", code: "" },
  { name: "kurdish.", code: "" },
  { name: "nederland", code: "" },
  { name: "sanskrit", code: "sa" },
  { name: "english/ russian /francia /españa", code: "" },
  { name: "hakka", code: "hak" },
  { name: "kyrgyz", code: "" },
  { name: "euskera", code: "" },
  { name: "ingles español", code: "" },
  { name: "isizulu", code: "" },
  { name: "hausa", code: "ha" },
  { name: "kiswahili", code: "" },
  { name: "indian", code: "" },
  { name: "bashkir", code: "ba" },
  { name: "welsh", code: "cy" },
  { name: "maori", code: "mi" },
  { name: "sepedi", code: "" },
  { name: "uzbek", code: "uz" },
  { name: "xitsonga", code: "" },
  { name: "global", code: "" },
  { name: "papiamentu", code: "" },
  { name: "occitan", code: "oc" },
  { name: "ger", code: "" },
  { name: "romani", code: "" },
  { name: "samoan", code: "sm" },
  { name: "carpatho-rusyn", code: "" },
  { name: "english spanish", code: "" },
  { name: "schweizerdeutsch", code: "" },
  { name: "česky", code: "" },
  { name: "язык: ру", code: "" },
  { name: "español paraguay", code: "" },
  { name: "rock", code: "" },
  { name: "ру", code: "" },
  { name: "burmese", code: "my" },
  { name: "shqip", code: "" },
  { name: "china", code: "" },
  { name: "english hindi", code: "" },
  { name: "arabic.", code: "" },
  { name: "pigin", code: "" },
  { name: "belge", code: "" },
  { name: "hawaiian", code: "" },
  { name: "latino", code: "" },
  { name: "sesotho", code: "" },
  { name: "australian", code: "" },
  { name: "setswana", code: "" },
  { name: "ภาษาไทย", code: "" },
  { name: "yiddish", code: "yi" },
  { name: "marathi", code: "mr" },
  { name: "esperanto", code: "eo" },
  { name: "brazillian", code: "" },
  { name: "canadian", code: "" },
  { name: "africa", code: "" },
  { name: "castilian", code: "" },
  { name: "españa", code: "" },
  { name: "angol", code: "" },
  { name: "lumasaba luganda english", code: "" },
  { name: "английский русский", code: "" },
  { name: "luganda english", code: "" },
  { name: "romansh", code: "rm" },
  { name: "frances", code: "" },
  { name: "xhosa", code: "xh" },
  { name: "maltese", code: "mt" },
  { name: "lingala", code: "ln" },
  { name: "kölscher dialekt", code: "" },
  { name: "yugoslavian", code: "" },
  { name: "jawa", code: "" },
  { name: "guarani", code: "gn" },
  { name: "malagasy", code: "mg" },
  { name: "various filipino languages", code: "" },
  { name: "asturian", code: "ast" },
  { name: "80s", code: "" },
  { name: "assamese", code: "as" },
  { name: "arapça", code: "" },
  { name: "aboriginal languages", code: "" },
  { name: "various languages", code: "" },
  { name: "chaoshan dialect", code: "" },
  { name: "fulani", code: "" },
  { name: "pop music", code: "" },
  { name: "sami", code: "" },
  { name: "französich", code: "" },
  { name: "punjab", code: "" },
  { name: "portoguese", code: "" },
  { name: "türkish", code: "" },
  { name: "portugues brasil", code: "" },
  { name: "bisaya", code: "" },
  { name: "#english", code: "" },
  { name: "tshivenda", code: "" },
  { name: "tonga", code: "to" },
  { name: "canada", code: "" },
  { name: "español españa", code: "" },
  { name: "teochew", code: "" },
  { name: "te reo maori", code: "" },
  { name: "español asunción", code: "" },
  { name: "cree", code: "cr" },
  { name: "others", code: "" },
  { name: "siswati", code: "" },
  { name: "engels", code: "" },
  { name: "san salvador", code: "" },
  { name: "bahasa sunda", code: "" },
  { name: "online radio", code: "" },
  { name: "discography", code: "" },
  { name: "bahasa jawa", code: "" },
  { name: "urdu/punjabi/seraiki", code: "" },
  { name: "sindhi", code: "sd" },
  { name: "englisg", code: "" },
  { name: "sint maarten", code: "" },
  { name: "tahitian", code: "ty" },
  { name: "romany", code: "" },
  { name: "sächsisch", code: "" },
  { name: "swiss", code: "" },
  { name: "suomi", code: "" },
  { name: "lower sorbian", code: "dsb" },
  { name: "sinhalese", code: "" },
  { name: "latviešu", code: "" },
  { name: "lebanese", code: "" },
  { name: "limburgs", code: "" },
  { name: "украина", code: "" },
  { name: "latinoamerica", code: "" },
  { name: "татарский", code: "" },
  { name: "russian/yakut", code: "" },
  { name: "standard moroccan amazigh", code: "" },
  { name: "sardinian", code: "sc" },
  { name: "ladin", code: "" },
  { name: "seychellois creole", code: "" },
  { name: "lliones", code: "" },
  { name: "lugwere", code: "" },
  { name: "tamaulipas", code: "" },
  { name: "multiculti", code: "" },
  { name: "nahuatl", code: "" },
  { name: "nderlands", code: "" },
  { name: "upper sorbian", code: "hsb" },
  { name: "nedersaksisch", code: "" },
  { name: "nemet", code: "" },
  { name: "pacific", code: "" },
  { name: "outro", code: "" },
  { name: "turkmen", code: "tk" },
  { name: "ossetian", code: "os" },
  { name: "only music", code: "" },
  { name: "novokuznetzk", code: "" },
  { name: "palestinian", code: "" },
  { name: "pedro juan caballero", code: "" },
  { name: "pigeon english", code: "" },
  { name: "roma", code: "" },
  { name: "tigrigna", code: "" },
  { name: "porguês", code: "" },
  { name: "malgache", code: "" },
  { name: "torres strait creole", code: "" },
  { name: "slowenisch", code: "" },
  { name: "malti", code: "" },
  { name: "mauritian creole", code: "" },
  { name: "ml", code: "" },
  { name: "ua", code: "" },
  { name: "por", code: "" },
  { name: "udmurt", code: "" },
  { name: "usa", code: "" },
  { name: "colombo", code: "" },
  { name: "bislama", code: "bi" },
  { name: "fante", code: "" },
  { name: "arabesk", code: "" },
  { name: "furlan", code: "" },
  { name: "bonaire", code: "" },
  { name: "chill", code: "" },
  { name: "español uruguay", code: "" },
  { name: "anguilla", code: "" },
  { name: "español ingles", code: "" },
  { name: "brasileiro", code: "" },
  { name: "espana", code: "" },
  { name: "iranian", code: "" },
  { name: "isindebele", code: "" },
  { name: "http://stream-uk1.radioparadise.com:80/aac-32", code: "" },
  { name: "hrvatska", code: "" },
  { name: "bayrisch", code: "" },
  { name: "haryanvi", code: "" },
  { name: "bavarian", code: "bar" },
  { name: "berbere", code: "" },
  { name: "frenchhttps://rfiswahili96k.ice.infomaniak.ch/rfis", code: "" },
  { name: "finland", code: "" },
  { name: "finish", code: "" },
  { name: "fijian hindi", code: "" },
  { name: "fries", code: "" },
  { name: "bicolano", code: "" },
  { name: "hits", code: "" },
  { name: "fijian", code: "fj" },
  { name: "fge spain", code: "" },
  { name: "isixhosa", code: "" },
  { name: "brezhoneg", code: "" },
  { name: "english russian", code: "" },
  { name: "e", code: "" },
  { name: "gallo", code: "" },
  { name: "germanhttps://stream.laut.fm/deutrockosterreich", code: "" },
  { name: "english - twi", code: "" },
  { name: "1", code: "" },
  { name: "+7 languages", code: "" },
  { name: "#japan", code: "" },
  { name: "gallego", code: "" },
  { name: "canadian french", code: "" },
  { name: "caribbean english", code: "" },
  { name: "音乐", code: "" },
  { name: "korea", code: "" },
  { name: "gagauz", code: "" },
  { name: "128 brazilian portuguese", code: "" },
  { name: "dhivehi", code: "" },
  { name: "catalán", code: "" },
  { name: "java", code: "" },
  { name: "espa", code: "" },
  { name: "english/tagalog", code: "" },
  { name: "gaeilge", code: "" },
  { name: "dansk/oldnordisk", code: "" },
  { name: "english/sotho/afrikaans", code: "" },
  { name: "aka bo", code: "" },
  { name: "gascon", code: "" },
  { name: "dialects", code: "" },
  { name: "silesian", code: "" },
  { name: "chhattisgarhi", code: "" },
  { name: "tamazight", code: "" },
  { name: "cochin", code: "" },
  { name: "te reo", code: "" },
  { name: "talk", code: "" },
  { name: "cassubian", code: "" },
  { name: "chipewyan", code: "" },
  { name: "coatian", code: "" },
  { name: "chuvash", code: "cv" },
  { name: "tachelhite", code: "" },
  { name: "swahili/", code: "" },
  { name: "cornish", code: "kw" },
  { name: "soft", code: "" },
  { name: "неизвестен", code: "" },
  { name: "dan", code: "" },
  { name: "desi", code: "" },
  { name: "encarnación", code: "" },
  { name: "duits", code: "" },
  { name: "dutch colombo", code: "" },
  { name: "sing along", code: "" },
  { name: "eesti", code: "" },
  { name: "egnlish", code: "" },
  { name: "shimaoré", code: "" },
  { name: "eight additional languages", code: "" },
  { name: "eletrica", code: "" },
  { name: "somali", code: "so" },
  { name: "dai language", code: "" },
  { name: "south asian languages", code: "" },
  { name: "swabian", code: "swg" },
  { name: "sv", code: "" },
  { name: "coronel oviedo", code: "" },
  { name: "corsican", code: "co" },
  { name: "sranan tongo", code: "" },
  { name: "spsnish", code: "" },
  { name: "spanol", code: "" },
  { name: "spanish saba", code: "" },
  { name: "corsu", code: "" },
  { name: "spani", code: "" },
  { name: "span", code: "" },
  { name: "creol", code: "" },
  { name: "south slavey", code: "" },
  { name: "en gb", code: "" },
  { name: "tlicho", code: "" },
  { name: "afghan", code: "" },
  { name: "śląski", code: "" },
  { name: "alemanha", code: "" },
  { name: "zeelandic", code: "" },
  { name: "zaiwa", code: "" },
  { name: "yupik", code: "" },
  { name: "amazigh", code: "" },
  { name: "yucatec maya", code: "" },
  { name: "anq", code: "" },
  { name: "yeruoba", code: "" },
  { name: "anserma", code: "" },
  { name: "apiaka", code: "" },
  { name: "wolof", code: "wo" },
  { name: "ar", code: "" },
  { name: "arabi", code: "" },
  { name: "acadian french", code: "" },
  { name: "испанский", code: "" },
  { name: "德语", code: "" },
  { name: "師傅傅", code: "" },
  { name: "国语", code: "" },
  { name: "中国", code: "" },
  { name: "язык: русский английский", code: "" },
  { name: "10 additional languages", code: "" },
  { name: "111", code: "" },
  { name: "чукотский", code: "" },
  { name: "церковнославянский", code: "" },
  { name: "123", code: "" },
  { name: "укр", code: "" },
  { name: "српски", code: "" },
  { name: "17 addtional languages", code: "" },
  { name: "осетинский", code: "" },
  { name: "молдавский", code: "" },
  { name: "astur-leonese", code: "" },
  { name: "ateso", code: "" },
  { name: "vaporwave", code: "" },
  { name: "twi", code: "tw" },
  { name: "turkt", code: "" },
  { name: "bohemian", code: "" },
  { name: "bollywood", code: "" },
  { name: "tule kaweah yokuts", code: "" },
  { name: "tshivenḓa", code: "" },
  { name: "tshiluba", code: "" },
  { name: "brabants", code: "" },
  { name: "tongan", code: "" },
  { name: "konkani", code: "" },
  { name: "tigrinya", code: "ti" },
  { name: "bulgaria", code: "" },
  { name: "tigre", code: "" },
  { name: "cajun", code: "" },
  { name: "cantonce", code: "" },
  { name: "tyvan", code: "" },
  { name: "bering aleut", code: "" },
  { name: "uzbek،russian", code: "" },
  { name: "australian indigenous", code: "" },
  { name: "aymara", code: "ay" },
  { name: "azer", code: "" },
  { name: "us", code: "" },
  { name: "urhobo", code: "" },
  { name: "azeri", code: "" },
  { name: "azr", code: "" },
  { name: "banjar", code: "" },
  { name: "upper chinook", code: "" },
  { name: "ungarisch", code: "" },
  { name: "ukrainisch", code: "" },
  { name: "bearnese", code: "" },
  { name: "ucrânia", code: "" },
  { name: "bengoli", code: "" },
  { name: "capiznon", code: "" },
  { name: "engish", code: "" },
  { name: "gwich'in", code: "" },
  { name: "hindu", code: "" },
  { name: "māori", code: "" },
  { name: "muromian", code: "" },
  { name: "moselle romance", code: "" },
  { name: "holland", code: "" },
  { name: "monoglian", code: "" },
  { name: "http://wdr-1live-live.icecast.wdr.de", code: "" },
  { name: "hun", code: "" },
  { name: "id", code: "" },
  { name: "minang", code: "" },
  { name: "mexicano", code: "" },
  { name: "messapic", code: "" },
  { name: "igbo", code: "ig" },
  { name: "masurian", code: "" },
  { name: "illonggo", code: "" },
  { name: "navajo", code: "nv" },
  { name: "hindi english assamese", code: "" },
  { name: "norvegian\\", code: "" },
  { name: "northern manx", code: "" },
  { name: "north slavey", code: "" },
  { name: "haiti creole", code: "" },
  { name: "norn", code: "" },
  { name: "noric", code: "" },
  { name: "noongar aboriginal", code: "" },
  { name: "noongar", code: "" },
  { name: "ngakarimojong", code: "" },
  { name: "new orleans louisiana", code: "" },
  { name: "nethe", code: "" },
  { name: "hausa l", code: "" },
  { name: "hh", code: "" },
  { name: "hin", code: "" },
  { name: "hind", code: "" },
  { name: "ilokano", code: "" },
  { name: "manx", code: "gv" },
  { name: "lisu", code: "" },
  { name: "kashubian", code: "" },
  { name: "kelantanese malay", code: "" },
  { name: "lietuvių", code: "" },
  { name: "keski-suomi", code: "" },
  { name: "laz", code: "" },
  { name: "kikongo", code: "" },
  { name: "kikuyu swahili", code: "" },
  { name: "latvia", code: "" },
  { name: "kinand", code: "" },
  { name: "kirmanci", code: "" },
  { name: "kiwi", code: "" },
  { name: "ladino", code: "" },
  { name: "komi", code: "kv" },
  { name: "kroatisch", code: "" },
  { name: "kashmiri", code: "ks" },
  { name: "kampampangan", code: "" },
  { name: "ilonggo", code: "" },
  { name: "indigenous languages", code: "" },
  { name: "inuktituk", code: "" },
  { name: "inuvialuktun", code: "" },
  { name: "irani", code: "" },
  { name: "iraqi turkmen", code: "" },
  { name: "jamaicaans-patois", code: "" },
  { name: "jamaican", code: "" },
  { name: "japones", code: "" },
  { name: "lugisu", code: "" },
  { name: "juma", code: "" },
  { name: "kachin", code: "" },
  { name: "lower arrernte", code: "" },
  { name: "kalaallisut", code: "kl" },
  { name: "louisiana french", code: "" },
  { name: "kupsabiny", code: "" },
  { name: "engleza", code: "" },
  { name: "español in catalán", code: "" },
  { name: "quiché", code: "" },
  { name: "españot", code: "" },
  { name: "qirimtatar", code: "" },
  { name: "espsñol", code: "" },
  { name: "f", code: "" },
  { name: "pt-pt", code: "" },
  { name: "potuguese", code: "" },
  { name: "portuguêsa", code: "" },
  { name: "fench", code: "" },
  { name: "portugués", code: "" },
  { name: "portuguese brazillian", code: "" },
  { name: "portuguese brazil", code: "" },
  { name: "fra", code: "" },
  { name: "portuges", code: "" },
  { name: "españo", code: "" },
  { name: "esapa", code: "" },
  { name: "engli", code: "" },
  { name: "englidh", code: "" },
  { name: "engligh", code: "" },
  { name: "san miguel", code: "" },
  { name: "englisgh", code: "" },
  { name: "samba e pagode", code: "" },
  { name: "sakha", code: "" },
  { name: "saint lucian creole", code: "" },
  { name: "s", code: "" },
  { name: "russian/", code: "" },
  { name: "rossia", code: "" },
  { name: "română end english", code: "" },
  { name: "englisj", code: "" },
  { name: "englsh", code: "" },
  { name: "esan", code: "" },
  { name: "portu", code: "" },
  { name: "francia", code: "" },
  { name: "pacifica multi ethnic", code: "" },
  { name: "p", code: "" },
  { name: "garifuna", code: "" },
  { name: "oscan", code: "" },
  { name: "oromo amharic somali", code: "" },
  { name: "originarios", code: "" },
  { name: "geopn", code: "" },
  { name: "old novgorod", code: "" },
  { name: "ojibwa", code: "oj" },
  { name: "oilsjters", code: "" },
  { name: "ghana", code: "" },
  { name: "greel", code: "" },
  { name: "nyungar", code: "" },
  { name: "nyoongar", code: "" },
  { name: "nuxalk", code: "" },
  { name: "galaic–portuguese", code: "" },
  { name: "pali", code: "pi" },
  { name: "portguese", code: "" },
  { name: "francés", code: "" },
  { name: "polynesia", code: "" },
  { name: "frysk", code: "" },
  { name: "po", code: "" },
  { name: "fränkisch", code: "" },
  { name: "pfälzisch", code: "" },
  { name: "pewhitsdesi", code: "" },
  { name: "pewhits", code: "" },
  { name: "pew", code: "" },
  { name: "gagana samoa", code: "" },
  { name: "pazeh", code: "" },
  { name: "pashto /urdu", code: "" },
  { name: "pashto", code: "" },
  { name: "paraguay", code: "" },
  { name: "gujurati", code: "" },
];
